---
title: "Human Freedom Index Project"
author: "Team Platypus: Lynne Wang, Neel Gajjar, Kate Neal"
output: pdf_document
---

```{r packages-data, warning=FALSE, message=FALSE}
library(tidyverse)
hfi <- read_csv("data/hfi_cc_2019.csv") 
```

```{r glimpse}
glimpse(hfi)
```

### Question 1

How has overall freedom around the world changed over time?

```{r q1, warning=FALSE, message=FALSE}
hfscore_by_year <- hfi %>% 
  filter(hf_score != "-") %>% 
  group_by(year) %>% 
  summarize(mean_hf = mean(as.numeric(hf_score)))

ggplot(data = hfscore_by_year, 
       aes(x = as.factor(year), y = mean_hf, group = 1)) +
  geom_line(stat = "identity") +
  ylim(6.75, 7.25)
```

### Question 2

How has overall freedom in the U.S. and China changed over time?

```{r q2, warning=FALSE, message=FALSE}
hfscore_china_us <- hfi %>% 
  filter(hf_score != "-" & 
           (countries == "China" | countries == "United States")) %>% 
  group_by(year, countries) %>% 
  summarize(mean_hf = mean(as.numeric(hf_score)))

ggplot(data = hfscore_china_us, 
       aes(x = as.factor(year), y = mean_hf, group = countries, color = countries)) +
  geom_line(stat = "identity")
```

### Question 3

In countries with the highest overall freedom scores, which freedoms are particularly high?

```{r q3, warning=FALSE, message=FALSE}
hfi %>% 
  filter(hf_rank != "-") %>% 
  group_by(countries) %>% 
  mutate(avg_rank = mean(as.numeric(hf_rank))) %>% 
  distinct(countries, avg_rank) %>% 
  arrange(desc(avg_rank)) %>% 
  summarize(countries, avg_rank)
```

### Question 4

What is the correlation between economic and personal freedom?

```{r q4}
corr_efpf <- hfi %>% 
  filter(pf_score != "-" & ef_score != "-") %>% 
  group_by(countries) %>% 
  mutate(corr_ef_pf = cor(as.numeric(ef_score), as.numeric(pf_score))) %>% 
  distinct(countries, corr_ef_pf) %>% 
  summarize(countries, corr_ef_pf)

ggplot(data = corr_efpf, aes(x = corr_ef_pf)) +
  geom_histogram(bins = 20)
```

